name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: 0.13.6
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  equatable: ^2.0.5
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/images/
    - assets/page-1/images/whatsapp-image-2023-04-04-at-2126.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-2.png
    - assets/page-1/images/building2-1.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/image-6-jnn.png
    - assets/page-1/images/whatsapp-image-2023-04-04-at-842-1.png
    - assets/page-1/images/image-7-Hga.png
    - assets/page-1/images/receive.png
    - assets/page-1/images/i-object-tools-scroll.png
    - assets/page-1/images/image-7-t14.png
    - assets/page-1/images/i-gaming-house.png
    - assets/page-1/images/image-6-Hvv.png
    - assets/page-1/images/building.png
    - assets/page-1/images/profile-1.png
    - assets/page-1/images/notif-1.png
    - assets/page-1/images/i-gaming-house-5mQ.png
    - assets/page-1/images/whatsapp-image-2023-04-04-at-2125.png
    - assets/page-1/images/color-hunt-palette-06283d1363df47b5ffdff6ff-1.png
    - assets/page-1/images/whatsapp-image-2023-04-04-at-2126-ts8.png
    - assets/page-1/images/image-24.png
    - assets/page-1/images/i-object-tools-scroll-ovn.png
    - assets/page-1/images/image-25.png
    - assets/page-1/images/profile2-1.png
    - assets/page-1/images/edit-1.png
    - assets/page-1/images/whatsapp-image-2023-04-04-at-2125-iEJ.png
    - assets/page-1/images/image-7-hvn.png
    - assets/page-1/images/image-6-vMU.png
    - assets/page-1/images/color-hunt-palette-1b262c0f4c753282b8bbe1fa-1.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1.png
    - assets/page-1/images/image-6-uDG.png
    - assets/page-1/images/i-gaming-house-UDc.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1-f2W.png
    - assets/page-1/images/component.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/intersect.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1-wWv.png
    - assets/page-1/images/image-7-RU2.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/auto-group-en3h.png
    - assets/page-1/images/i-gaming-house-8Ea.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1-EYW.png
    - assets/page-1/images/whatsapp-image-2023-04-04-at-842-2.png
    - assets/page-1/images/auto-group-euyp.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/i-gaming-house-nnr.png
    - assets/page-1/images/subtract.png
    - assets/page-1/images/component-zP8.png
    - assets/page-1/images/receive-fXC.png
    - assets/page-1/images/intersect-15G.png
    - assets/page-1/images/chevronleft.png
    - assets/page-1/images/chevronleft-LNS.png
    - assets/page-1/images/component-swL.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-2-vkW.png
    - assets/page-1/images/group-66.png
    - assets/page-1/images/image-26.png
    - assets/page-1/images/receive-Qwp.png
    - assets/page-1/images/.png
    - assets/page-1/images/auto-group-ghef.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/person2-1.png
    - assets/page-1/images/subtract-bav.png
    - assets/page-1/images/i-commerce-creditcard.png
    - assets/page-1/images/icon-CiJ.png
    - assets/page-1/images/i-gaming-house-jTL.png
    - assets/page-1/images/auto-group-tyn7.png
    - assets/page-1/images/auto-group-wpmm.png
    - assets/page-1/images/i-human-person.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/image-6-JwY.png
    - assets/page-1/images/i-gaming-house-zrJ.png
    - assets/page-1/images/image-27.png
    - assets/page-1/images/i-gaming-house-WBg.png
    - assets/page-1/images/whatsapp-image-2023-04-04-at-1913.png
    - assets/page-1/images/group-66-hee.png
    - assets/page-1/images/i-gaming-house-whG.png
    - assets/page-1/images/i-time-clockarrowcirclepath.png
    - assets/page-1/images/auto-group-8igx.png
    - assets/page-1/images/receive-U2r.png
    - assets/page-1/images/i-gaming-house-DFL.png
    - assets/page-1/images/image-23.png
    - assets/page-1/images/component-Y22.png
    - assets/page-1/images/auto-group-ir8b.png
    - assets/page-1/images/i-object-tools-briefcase.png
    - assets/page-1/images/icon-PaN.png
    - assets/page-1/images/person-1.png
    - assets/page-1/images/i-object-tools-briefcase-srE.png
    - assets/page-1/images/chevronleft-5jL.png
    - assets/page-1/images/profile-2.png
    - assets/page-1/images/i-object-tools-briefcase-4wx.png
    - assets/page-1/images/profile-2-T1Q.png
    - assets/page-1/images/auto-group-poso.png
    - assets/page-1/images/profile-1-vYE.png
    - assets/page-1/images/magnifyingglass.png
    - assets/page-1/images/receive-THG.png
    - assets/page-1/images/i-gaming-house-eea.png
    - assets/page-1/images/logo.png
    - assets/page-1/images/component-MDY.png
    - assets/page-1/images/auto-group-hscf.png
    - assets/page-1/images/i-object-tools-briefcase-rRC.png
    - assets/page-1/images/receive-SL6.png
    - assets/page-1/images/auto-group-wgmd.png
    - assets/page-1/images/image-7-8rz.png
    - assets/page-1/images/icon-8UE.png
    - assets/page-1/images/component-oMQ.png
    - assets/page-1/images/image-7-zzA.png
    - assets/page-1/images/profile-2-AA2.png
    - assets/page-1/images/image-7-rBg.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/image-7-jaW.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1-STY.png
    - assets/page-1/images/image-7-SGW.png
    - assets/page-1/images/i-gaming-house-dYa.png
    - assets/page-1/images/image-7-nyC.png
    - assets/page-1/images/image-7-v62.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1-t5L.png
    - assets/page-1/images/notif-1-xEr.png
    - assets/page-1/images/whatsapp-image-2023-04-04-at-2126-nnS.png
    - assets/page-1/images/profile-2-hWn.png
    - assets/page-1/images/profile-2-xUN.png
    - assets/page-1/images/image-7-2vS.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1-4FG.png
    - assets/page-1/images/i-arrows-chevrondown.png
    - assets/page-1/images/profile-2-hhx.png
    - assets/page-1/images/image-7-nPG.png
    - assets/page-1/images/moneylogodesignstemplatevectorfinancelogodesignsvector1-removebg-preview-1-pii.png
    - assets/page-1/images/edit-1-pj8.png
    - assets/page-1/images/image-7-Rx2.png
    - assets/page-1/images/profile2-1-s1x.png
    - assets/page-1/images/profile-2-buY.png
    - assets/page-1/images/dollar.png
    - assets/page-1/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
